### ISSUE TITLE
modpack doesn't install

### ISSUE THREAD

**Issue by aquilesconnor** [DrParadox7/Lost-Era-Modpack#26] opened 2022-02-08 18:49 UTC
### Type of Instance

Single Player

### Installation Target

Your Own Computer or Laptop

### Your Actions

when I download modpack and open it in minecraft launcher it starts downloading the external files but there is a time when it just stops and I've already tried turning off the Windows anti virus and it still doesn't work

### Your Pack Version

1.4.4

### Required Logs

![Uploading 16443461268292607002473908118634.jpg…]()

### Final Checklist

- [X] I have provided all the required logs.
- [X] I searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this crash consistently by following the exact steps I described above.

**Comment by SwedishKaito** [comment] 2022-02-08 18:54
Hey! Feel free to check #25 , since that has the issue reported already and the workaround!

**Comment by DrParadox7** [comment] 2022-02-08 18:59
Duplicate of #25.
We’re working on it and should hopefully be fixed soon.

**Closed by DrParadox7** 2022-02-08 18:59 UTC
