### ISSUE TITLE
AE2 Inscriber spawning in veins

### ISSUE THREAD

**Issue by Lucatowalker** [DrParadox7/Lost-Era-Modpack#86] opened 2023-10-01 22:03 UTC
### Your Pack Version

1.6.2

### Type of Instance

Single Player

### Your Expectation

I expected normal, non-technological ore veins in my mining session
![Inscriber vein](https://github.com/DrParadox7/Lost-Era-Modpack/assets/43684056/3a65d8d0-1157-4db7-b108-202c1e058af2)

### The Reality

AE2 Inscribers spawn in ore veins. This occurred on an ordinary singleplayer world with no changes to config or worldtype.

### Your Proposal

Find which config is responsible for inscriber veins and fix it. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by SwedishKaito** [comment] 2023-10-01 22:36
Already reported and fixed in #83 .

**Comment by DrParadox7** [comment] 2023-10-01 22:37
Duplicate of #83

**Closed by DrParadox7** 2023-10-01 22:37 UTC
